## General purpose build tooling
# (unused)
#load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## Android Stuff
android_sdk_repository(name = "androidsdk")


RULES_ANDROID_NDK_COMMIT= "877c68ef34c9f3353028bf490d269230c1990483"
http_archive(
    name = "rules_android_ndk",
    url = "https://github.com/bazelbuild/rules_android_ndk/archive/%s.zip" % RULES_ANDROID_NDK_COMMIT,
    strip_prefix = "rules_android_ndk-%s" % RULES_ANDROID_NDK_COMMIT,
)
load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")
android_ndk_repository(name = "androidndk")

## QuickJS
http_archive(
  name = "quickjs",
  url = "https://github.com/bellard/quickjs/archive/refs/heads/master.zip",
  sha256 = "94e322bf27d5def3eefeab485ff79ae1a952b4563dd155263557b56038e9b6e0",
  
  strip_prefix = "quickjs-master",

  build_file = "@//:quickjs.BUILD"
)
## /QuickJS
