/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_Jni */

#ifndef _Included_com_app_Jni
#define _Included_com_app_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_Jni
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_app_Jni_greet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
